services:
  ingestion-service:
    build: ./ingestion-service
    ports:
      - "3000:3000"
    volumes:
      - ./ingestion-service:/app
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    env_file:
      - .env

  analysis-service:
    build: ./analysis-service
    volumes:
      - ./analysis-service:/app
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    env_file:
      - .env

  orchestrator-service:
    build: ./orchestrator-service
    volumes:
      - ./orchestrator-service:/app
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  frontend-service:
    build: ./frontend-service
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-service:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - ingestion-service
